import os
import time
from pathlib import Path
from docx import Document
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import RtfFormatter
import structlog

logger = structlog.get_logger()
DOCS_DIR = Path.home() / "DevShield_Docs"
DOCS_DIR.mkdir(exist_ok=True)

class DocGenerator:
    def __init__(self):
        self.doc_dir = DOCS_DIR
        
    def generate_readme(self, code: str, language: str, project_name: str) -> str:
        return f"""# {project_name}

## Overview
Auto-generated DevShield documentation for {project_name}.

## Installation
```bash
# Setup dependency structures for {language}
```

## API Reference
Code structure provided below:
```{language}
{code[:200]}...
```

## Security Considerations
- Validate all incoming arguments against semantic limits.
- Ensure cryptographic material is provided safely via ENV strings.
"""

    def generate_word_doc(self, code: str, readme: str, project_name: str) -> str:
        doc = Document()
        doc.add_heading(f'DevShield Security & Architecture Report: {project_name}', 0)
        
        doc.add_heading('1. Overview', level=1)
        doc.add_paragraph("This document was autonomously generated by DevShield AI Document Intelligence Engine.")
        
        doc.add_heading('2. README Segment', level=1)
        doc.add_paragraph(readme)
        
        doc.add_heading('3. Code Reference', level=1)
        doc.add_paragraph(code)
        
        ts = int(time.time())
        path = self.doc_dir / f"{project_name}_{ts}.docx"
        doc.save(path)
        logger.info(f"Generated Word doc at {path}")
        return str(path)

    def generate_pdf(self, code: str, readme: str, project_name: str) -> str:
        ts = int(time.time())
        path = self.doc_dir / f"{project_name}_{ts}.pdf"
        
        doc = SimpleDocTemplate(str(path), pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []
        
        elements.append(Paragraph(f"DevShield Report: {project_name}", styles['Title']))
        elements.append(Spacer(1, 12))
        
        elements.append(Paragraph("README Content", styles['Heading1']))
        elements.append(Paragraph(readme[:500], styles['Normal']))
        elements.append(Spacer(1, 12))
        
        elements.append(Paragraph("Code Highlights", styles['Heading1']))
        clean_code = code[:1000] if len(code) > 1000 else code
        elements.append(Preformatted(clean_code, styles['Code']))
        
        doc.build(elements)
        logger.info(f"Generated PDF doc at {path}")
        return str(path)

    def fix_document_formatting(self, file_path: str) -> dict:
        fixes = []
        try:
            doc = Document(file_path)
            for p in doc.paragraphs:
                if not p.style.name.startswith('Heading') and p.runs:
                    if p.runs[0].font.name != "Arial":
                        for r in p.runs:
                            r.font.name = "Arial"
                        fixes.append("Standardized font to Arial")
            fixed_path = file_path.replace(".docx", "_fixed.docx")
            doc.save(fixed_path)
            return {"file_path": fixed_path, "fixes": list(set(fixes))}
        except Exception as e:
            logger.error(f"Failed to fix doc: {e}")
            return {"file_path": file_path, "fixes": []}

    def repair_word_document(self, file_path: str) -> str:
        try:
            doc = Document(file_path)
            clean = Document()
            clean.add_heading("Repaired Document", 0)
            for p in doc.paragraphs:
                if p.text.strip():
                    clean.add_paragraph(p.text)
                    
            repaired_path = file_path.replace(".docx", "_repaired.docx")
            clean.save(repaired_path)
            return repaired_path
        except Exception:
            fallback = Document()
            fallback.add_heading("Recovered Content", 0)
            fallback.add_paragraph("Original document xml was heavily malformed.")
            out = file_path.replace(".docx", "_recovered.docx")
            fallback.save(out)
            return out
